/* Generated by Yosys 0.65+57 (git sha1 9d0cdb855, g++ 12.5.0 -fPIC -O3) [cliffordwolf/yosys] */

(* top =  1  *)
(* src = "mem_complex_small.v:1.1-95.10" *)
module mem_complex_small(clk, we_w0, addr_w0, data_w0, we_w1, addr_w1, data_w1, addr_r0, data_r0, ce_r1, srst_r1, addr_r1, data_r1, addr_r2, data_r2, addr_r3, data_r3);
  (* src = "mem_complex_small.v:3.16-3.19" *)
  input clk;
  wire clk;
  (* src = "mem_complex_small.v:4.22-4.27" *)
  input [1:0] we_w0;
  wire [1:0] we_w0;
  (* src = "mem_complex_small.v:5.22-5.29" *)
  input [4:0] addr_w0;
  wire [4:0] addr_w0;
  (* src = "mem_complex_small.v:6.22-6.29" *)
  input [3:0] data_w0;
  wire [3:0] data_w0;
  (* src = "mem_complex_small.v:9.16-9.21" *)
  input we_w1;
  wire we_w1;
  (* src = "mem_complex_small.v:10.22-10.29" *)
  input [4:0] addr_w1;
  wire [4:0] addr_w1;
  (* src = "mem_complex_small.v:11.22-11.29" *)
  input [3:0] data_w1;
  wire [3:0] data_w1;
  (* src = "mem_complex_small.v:14.22-14.29" *)
  input [4:0] addr_r0;
  wire [4:0] addr_r0;
  (* src = "mem_complex_small.v:15.23-15.30" *)
  output [3:0] data_r0;
  wire [3:0] data_r0;
  (* src = "mem_complex_small.v:18.16-18.21" *)
  input ce_r1;
  wire ce_r1;
  (* src = "mem_complex_small.v:19.16-19.23" *)
  input srst_r1;
  wire srst_r1;
  (* src = "mem_complex_small.v:20.22-20.29" *)
  input [4:0] addr_r1;
  wire [4:0] addr_r1;
  (* src = "mem_complex_small.v:21.22-21.29" *)
  output [3:0] data_r1;
  wire [3:0] data_r1;
  (* src = "mem_complex_small.v:24.22-24.29" *)
  input [4:0] addr_r2;
  wire [4:0] addr_r2;
  (* src = "mem_complex_small.v:25.22-25.29" *)
  output [3:0] data_r2;
  wire [3:0] data_r2;
  (* src = "mem_complex_small.v:28.22-28.29" *)
  input [3:0] addr_r3;
  wire [3:0] addr_r3;
  (* src = "mem_complex_small.v:29.22-29.29" *)
  output [7:0] data_r3;
  wire [7:0] data_r3;
  (* src = "mem_complex_small.v:48.5-52.8" *)
  (* unused_bits = "2 3" *)
  wire [3:0] _00_;
  (* src = "mem_complex_small.v:48.5-52.8" *)
  wire [3:0] _01_;
  (* src = "mem_complex_small.v:48.5-52.8" *)
  (* unused_bits = "0 1" *)
  wire [3:0] _02_;
  (* src = "mem_complex_small.v:48.5-52.8" *)
  wire [3:0] _03_;
  (* src = "mem_complex_small.v:55.5-69.8" *)
  wire [4:0] _04_;
  (* src = "mem_complex_small.v:55.5-69.8" *)
  wire [3:0] _05_;
  (* src = "mem_complex_small.v:55.5-69.8" *)
  wire [3:0] _06_;
  (* src = "mem_complex_small.v:36.37-36.55" *)
  wire _07_;
  (* src = "mem_complex_small.v:37.38-37.48" *)
  wire _08_;
  (* src = "mem_complex_small.v:36.10-36.19" *)
  wire collision;
  (* src = "mem_complex_small.v:37.16-37.23" *)
  wire [1:0] we_w0_s;
  (* src = "mem_complex_small.v:33.15-33.18" *)
  reg [3:0] ram [25:10];
  always @(posedge clk) begin
    if (_06_[0])
      ram[_04_] <= _05_;
  end
  always @(posedge clk) begin
    if (_01_[0])
      ram[addr_w0][1:0] <= _00_[1:0];
    if (_03_[2])
      ram[addr_w0][3:2] <= _02_[3:2];
  end
  reg [3:0] _20_;
  reg [3:0] _21_;
  reg [7:0] _22_;
  always @(posedge clk) begin
    _20_ <= ram[addr_r2];
    if (_06_[0] && addr_r2 == _04_)
      _20_ <= _05_;
    if (ce_r1) begin
      _21_ <= ram[addr_r1];
      if (srst_r1)
        _21_ <= 4'hd;
    end
    _22_[3:0] <= ram[{ addr_r3, 1'h0 }];
    _22_[7:4] <= ram[{ addr_r3, 1'h1 }];
  end
  initial _20_ = 4'h9;
  assign data_r2 = _20_;
  assign data_r0 = ram[addr_r0];
  initial _21_ = 4'ha;
  assign data_r1 = _21_;
  initial _22_ = 8'hc3;
  assign data_r3 = _22_;
  assign we_w0_s = we_w0 & (* src = "mem_complex_small.v:37.27-37.50" *) { _08_, _08_ };
  assign _07_ = addr_w0 == (* src = "mem_complex_small.v:36.37-36.55" *) addr_w1;
  assign collision = we_w1 && (* src = "mem_complex_small.v:36.27-36.56" *) _07_;
  assign _08_ = ~ (* src = "mem_complex_small.v:37.38-37.48" *) collision;
  assign _06_[0] = we_w1 ? (* full_case = 32'd1 *) (* src = "mem_complex_small.v:57.13-57.18|mem_complex_small.v:57.9-59.12" *) 1'h1 : 1'h0;
  assign _05_ = we_w1 ? (* full_case = 32'd1 *) (* src = "mem_complex_small.v:57.13-57.18|mem_complex_small.v:57.9-59.12" *) data_w1 : 4'hx;
  assign _04_ = we_w1 ? (* full_case = 32'd1 *) (* src = "mem_complex_small.v:57.13-57.18|mem_complex_small.v:57.9-59.12" *) addr_w1 : 5'hxx;
  assign _03_[2] = we_w0_s[1] ? (* full_case = 32'd1 *) (* src = "mem_complex_small.v:51.13-51.23|mem_complex_small.v:51.9-51.59" *) 1'h1 : 1'h0;
  assign _02_ = we_w0_s[1] ? (* full_case = 32'd1 *) (* src = "mem_complex_small.v:51.13-51.23|mem_complex_small.v:51.9-51.59" *) { data_w0[3:2], 2'hx } : 4'hx;
  assign _01_[0] = we_w0_s[0] ? (* full_case = 32'd1 *) (* src = "mem_complex_small.v:50.13-50.23|mem_complex_small.v:50.9-50.59" *) 1'h1 : 1'h0;
  assign _00_ = we_w0_s[0] ? (* full_case = 32'd1 *) (* src = "mem_complex_small.v:50.13-50.23|mem_complex_small.v:50.9-50.59" *) { 2'h0, data_w0[1:0] } : 4'hx;
  assign _01_[3:1] = { 2'h0, _01_[0] };
  assign _06_[3:1] = { _06_[0], _06_[0], _06_[0] };
  assign { _03_[3], _03_[1:0] } = { _03_[2], 2'h0 };
endmodule
