/* Generated by Yosys 0.64+26 (git sha1 a54bca549-dirty, g++ 10.5.0 -fPIC -O3) [cliffordwolf/yosys] */

(* dynports =  1  *)
(* cells_not_processed =  1  *)
(* src = "test_mem.v:1.1-32.10" *)
module test_mem(clk, we, write_addr, write_data, read_addr, read_data);
  (* src = "test_mem.v:5.34-5.37" *)
  input clk;
  wire clk;
  (* src = "test_mem.v:8.34-8.36" *)
  input we;
  wire we;
  (* src = "test_mem.v:9.34-9.44" *)
  input [7:0] write_addr;
  wire [7:0] write_addr;
  (* src = "test_mem.v:10.34-10.44" *)
  input [7:0] write_data;
  wire [7:0] write_data;
  (* src = "test_mem.v:13.34-13.43" *)
  input [7:0] read_addr;
  wire [7:0] read_addr;
  (* src = "test_mem.v:14.34-14.43" *)
  output [7:0] read_data;
  wire [7:0] read_data;
  (* src = "test_mem.v:21.5-25.8" *)
  wire [7:0] _0_;
  (* src = "test_mem.v:21.5-25.8" *)
  wire [7:0] _1_;
  (* src = "test_mem.v:21.5-25.8" *)
  wire [7:0] _2_;
  (* src = "test_mem.v:18.26-18.29" *)
  reg [7:0] ram [255:0];
  always @(posedge clk) begin
    if (_2_[0])
      ram[_0_] <= _1_;
  end
  reg [7:0] _6_;
  always @(posedge clk) begin
    _6_ <= ram[read_addr];
  end
  assign read_data = _6_;
  assign _2_[0] = we ? (* full_case = 32'd1 *) (* src = "test_mem.v:22.13-22.15|test_mem.v:22.9-24.12" *) 1'h1 : 1'h0;
  assign _1_ = we ? (* full_case = 32'd1 *) (* src = "test_mem.v:22.13-22.15|test_mem.v:22.9-24.12" *) write_data : 8'hxx;
  assign _0_ = we ? (* full_case = 32'd1 *) (* src = "test_mem.v:22.13-22.15|test_mem.v:22.9-24.12" *) write_addr : 8'hxx;
  assign _2_[7:1] = { _2_[0], _2_[0], _2_[0], _2_[0], _2_[0], _2_[0], _2_[0] };
endmodule
